document.getElementById("resumedata").addEventListener('submit', (event) => {
    event.preventDefault();
    let resumeForm = document.getElementById('resumedata');
    let formData = new FormData(resumeForm);
    let userData = {};
    formData.forEach((value, key) => userData[key] = value);
    let template = document.getElementById("resumeTemplate");
    let t = template.content.cloneNode(true);
    t.querySelector("#namebox").textContent = userData["fnamebox"]+" "+userData["lnamebox"];
    t.querySelector("#emailbox").textContent = userData["emailbox"];
    t.querySelector("#phonebox").textContent = userData["phonebox"];
    t.querySelector("#skillsbox").textContent = userData["skillsbox"];
    t.querySelector("#eduname1").textContent = userData["eduname1"];
    t.querySelector("#edurole1").textContent = userData["edurole1"];
    t.querySelector("#eduyear1").textContent = userData["eduyear1"]; 
    t.querySelector("#eduname2").textContent = userData["eduname2"];
    t.querySelector("#edurole2").textContent = userData["edurole2"];
    t.querySelector("#eduyear2").textContent = userData["eduyear2"]; 
    t.querySelector("#eduname3").textContent = userData["eduname3"];
    t.querySelector("#edurole3").textContent = userData["edurole3"];
    t.querySelector("#eduyear3").textContent = userData["eduyear3"];
    t.querySelector("#exp1").textContent = userData["exprole1"]+"-"+userData["expname1"];
    t.querySelector("#exp2").textContent = userData["exprole2"]+"-"+userData["expname2"];
    t.querySelector("#projectname1").textContent = userData["projectname1"]+"-"+userData["projecttype1"];
    t.querySelector("#des1").textContent = userData["des1"];
    t.querySelector("#projectname2").textContent = userData["projectname2"]+"-"+userData["projecttype2"];
    t.querySelector("#des2").textContent = userData["des2"];
    let div = document.createElement("div");
    div.append(t);
    let data = div.innerHTML;
    document.body.innerHTML = data;
});